"""Tests for Iteration 8 notifications feature + regression checks."""
import os
import pytest
import requests

BASE_URL = os.environ["EXPO_PUBLIC_BACKEND_URL"].rstrip("/")


@pytest.fixture(scope="module")
def token():
    r = requests.post(f"{BASE_URL}/api/auth/dev-login", timeout=20)
    assert r.status_code == 200, r.text
    j = r.json()
    return j.get("session_token") or j.get("token") or j["access_token"]


@pytest.fixture(scope="module")
def auth_headers(token):
    return {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}


@pytest.fixture(scope="module", autouse=True)
def seed_data(auth_headers):
    # Make sure demo data exists
    r = requests.post(f"{BASE_URL}/api/seed", headers=auth_headers, timeout=30)
    assert r.status_code in (200, 201), r.text
    return r.json()


# ---- /api/notifications ----
class TestNotifications:
    def test_requires_auth(self):
        r = requests.get(f"{BASE_URL}/api/notifications", timeout=15)
        assert r.status_code == 401

    def test_returns_items_and_count(self, auth_headers):
        r = requests.get(f"{BASE_URL}/api/notifications", headers=auth_headers, timeout=20)
        assert r.status_code == 200, r.text
        body = r.json()
        assert "items" in body and "count" in body
        assert isinstance(body["items"], list)
        assert body["count"] == len(body["items"])

    def test_item_schema(self, auth_headers):
        r = requests.get(f"{BASE_URL}/api/notifications", headers=auth_headers, timeout=20)
        body = r.json()
        if not body["items"]:
            pytest.skip("No notifications generated by demo seed; aggregator coverage validated by next tests")
        sample = body["items"][0]
        for k in ("id", "type", "level", "title", "message"):
            assert k in sample, f"missing {k} in {sample}"
        assert sample["level"] in ("high", "medium", "low")
        assert sample["type"] in ("expiration", "penalty", "workflow_rejected", "esf_pending")

    def test_sorted_by_level(self, auth_headers):
        r = requests.get(f"{BASE_URL}/api/notifications", headers=auth_headers, timeout=20)
        items = r.json()["items"]
        rank = {"high": 0, "medium": 1, "low": 2}
        levels = [rank[i["level"]] for i in items]
        assert levels == sorted(levels), "Notifications not sorted by level"

    def test_aggregates_expiration_and_penalty_and_esf(self, auth_headers):
        """Verify aggregator covers all three alert types using existing demo data + adding an ESF non-compliant item."""
        # Pick an existing contract from notifications (penalty/expiration come from demo seed)
        r = requests.get(f"{BASE_URL}/api/notifications", headers=auth_headers, timeout=20)
        items = r.json()["items"]
        types_existing = {i["type"] for i in items}
        assert "expiration" in types_existing, f"No expiration alerts in demo: {types_existing}"
        assert "penalty" in types_existing, f"No penalty alerts in demo: {types_existing}"

        # Now add a non-compliant ESF item to verify ESF aggregator
        contracts = requests.get(f"{BASE_URL}/api/contracts", headers=auth_headers, timeout=10).json()
        assert contracts, "No contracts to attach ESF to"
        cid = contracts[0]["contract_id"]
        esf_payload = {"requirement": "TEST_ESF non-compliant", "compliant": False, "observations": "test"}
        er = requests.post(f"{BASE_URL}/api/contracts/{cid}/esf", headers=auth_headers, json=esf_payload, timeout=15)
        assert er.status_code in (200, 201), er.text
        r2 = requests.get(f"{BASE_URL}/api/notifications", headers=auth_headers, timeout=20)
        types_after = {i["type"] for i in r2.json()["items"]}
        assert "esf_pending" in types_after, f"ESF aggregator did not fire: {types_after}"


# ---- Regression checks ----
class TestRegression:
    def test_dashboard_still_works(self, auth_headers):
        r = requests.get(f"{BASE_URL}/api/dashboard", headers=auth_headers, timeout=20)
        assert r.status_code == 200, r.text
        body = r.json()
        # Sanity: should have totals or alerts
        assert isinstance(body, dict)

    def test_contracts_list(self, auth_headers):
        r = requests.get(f"{BASE_URL}/api/contracts", headers=auth_headers, timeout=20)
        assert r.status_code == 200
        assert isinstance(r.json(), list)

    def test_auth_me(self, auth_headers):
        r = requests.get(f"{BASE_URL}/api/auth/me", headers=auth_headers, timeout=10)
        assert r.status_code == 200
        assert "email" in r.json()

    def test_locale(self, auth_headers):
        r = requests.post(f"{BASE_URL}/api/auth/locale", headers=auth_headers, json={"locale": "es"}, timeout=10)
        assert r.status_code == 200

    def test_avatar_endpoint_exists(self, auth_headers):
        # GET avatar (default may 200 or 404). just ensure routed
        r = requests.get(f"{BASE_URL}/api/users/me/avatar", headers=auth_headers, timeout=10)
        assert r.status_code in (200, 204, 404)

    def test_share_link_create(self, auth_headers):
        # Pick an existing contract
        contracts = requests.get(f"{BASE_URL}/api/contracts", headers=auth_headers, timeout=10).json()
        if not contracts:
            pytest.skip("No contracts to create share link")
        cid = contracts[0]["contract_id"]
        r = requests.post(
            f"{BASE_URL}/api/contracts/{cid}/share-link",
            headers=auth_headers,
            json={"ttl_hours": 24, "scope": "read"},
            timeout=10,
        )
        assert r.status_code in (200, 201), r.text
        body = r.json()
        assert "url" in body or "token" in body
